# Hyper-parameters of Networks:
divide_and_rule: False               # whether use the divide-and-rule strategy
epoch: 11
gpu: 0
lr: 3e-4
not_fine_tuned: False                # do not fine-tune simclr True/False
use_ins_dia: False                  # whether use instructional diagram to strengthen representations or not
weight_decay: 10e-6

dataset:
  batch_size: 2
  data_path: ''
  num_works: 8

pretrained_emb:
  name: en_trf_bertbaseuncased_lg   # choices:en_vectors_web_lg, en_trf_robertabase_lg, en_trf_bertbaseuncased_lg
  size: 768

simclr:
  base_model: 'resnet50'            # choose resnet-xx model
  out_dim: 128
  checkpoints_folder: 'Oct13_11-08-36_lthpc/checkpoints/'


