# Hyper-parameters of Networks:
batch_size: 2
epoch: 11
gpu: 0
not_fine_tuned: False                # do not fine-tune simclr True/False

dataset:
  data_path: ''
  num_works: 8

pretrained_emb:
  name: en_trf_bertbaseuncased_lg   # choices:en_vectors_web_lg, en_trf_robertabase_lg, en_trf_bertbaseuncased_lg
  size: 768

simclr:
  base_model: 'resnet50'            # choose resnet-xx model
  out_dim: 128
  checkpoints_folder: 'Oct13_11-08-36_lthpc/checkpoints/'

dataset_use: 'dqa'
model: 'xtqa'
run_mode: 'train'