# Hyper-parameters of Networks:
batch_size: 2
epoch: 12
gpu: 0

dataset:
  data_path: ''
  num_works: 8

pretrained_emb:
  name: en_trf_bertbaseuncased_lg   # choices:en_vectors_web_lg, en_trf_robertabase_lg, en_trf_bertbaseuncased_lg
  size: 768